<section>
    <div class="row">
        <div class="col-md-12 text-right">
            <p>
                <a href="<?php echo $this->url(array(
                    'controller' => 'exposicao',
                    'action' => 'add'
                ), null, true); ?>" class="btn btn-success">
                    <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate("Crie sua exposição"); ?>
                </a>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p><?php echo $this->translate("Últimas Exposições"); ?></p>
            <hr />
        </div>
    </div>    
    <?php if ($this->exposicoes) : ?>
    <div class="row">         
        <?php foreach ($this->exposicoes as $exposicao) : ?>
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading small"><?php echo $exposicao->exposicao_nome; ?></div>
                <div class="panel-body small">
                    <div class="row">
                        <div class="col-md-6 text-left"><i class="glyphicon glyphicon-time"></i> <?php echo $exposicao->exposicao_data_criacao; ?> </div>
                        <div class="col-md-6 text-right"><i class="glyphicon glyphicon-pushpin"></i> <?php echo $exposicao->tipo_exposicao->tipo_exposicao; ?></div>
                        <hr />
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <img width="100%" src="<?php echo $this->baseUrl('/views/img/exposicao/capa/' . $exposicao->exposicao_capa); ?>" class="img img-responsive" />
                            <hr />
                        </div>
                    </div>
                    <div class="row">                               
                        <div class="col-md-12">
                            <i><?php echo $exposicao->exposicao_descricao; ?></i>
                        </div>
                    </div>  
                </div>
                <div class="panel-footer small">
                    <div class="row">
                        <div class="col-md-6 text-left">
                            <p><?php echo $exposicao->get_visualizacoes(); ?></p>
                            <i class="glyphicon glyphicon-star text-warning"></i>
                            <i class="glyphicon glyphicon-star text-warning"></i>
                            <i class="glyphicon glyphicon-star text-warning"></i>
                            <i class="glyphicon glyphicon-star-empty"></i>
                            <i class="glyphicon glyphicon-star-empty"></i>       
                        </div>
                        <div class="col-md-6 text-right small">                                   
                            <a href="<?php echo $this->url(array(
                                'controller' => 'exposicao',
                                'action' => 'open',
                                'exposicao' => $exposicao->exposicao_id
                            ), null, true); ?>" class="btn btn-success">ABRIR EXPOSIÇÃO</a>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>   
        <?php endforeach; ?>
    </div>    
    <?php endif; ?>
</section>

<!--
<section>
    <div class="row">
        <div class="col-md-12">
            <p><?php echo $this->translate("Os Grandes Artistas"); ?></p>
            <hr />
        </div>
    </div>
</section>
-->