<section>
    <div class="row">
        <div class="col-md-12 text-right">
            <p>
                <a class="btn btn-success">
                    <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate("Crie sua exposição"); ?>
                </a>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p><?php echo $this->translate("Últimas Exposições"); ?></p>
            <hr />
        </div>
    </div>    
    <div class="row">                
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading small">Conversíveis</div>
                <div class="panel-body small">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="#" title="Fernando Rodrigues">
                                <img src="<?php echo $this->baseUrl('views/img/eu.jpg'); ?>" class="img img-rounded img-responsive" />
                            </a>
                        </div>
                        <div class="col-md-8">
                            <p>
                                <i class="glyphicon glyphicon-time"></i> 19/08/2015 <br />                                                       
                            </p>
                            <p>
                                <i class="glyphicon glyphicon-user"></i> Fernando Rodrigues                             
                            </p>
                            <p>
                                <i class="glyphicon glyphicon-pushpin"></i> Obras de Arte
                            </p>                        
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12"><hr /></div>
                    </div>
                    <div class="row">                               
                        <div class="col-md-5">
                            <i>Descricao</i>
                        </div>
                        <div class="col-md-7">
                            <img src="<?php echo $this->baseUrl('views/img/monet.jpg'); ?>" class="img img-responsive" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12"><hr /></div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 text-left">
                            <i class="glyphicon glyphicon-star text-warning"></i>
                            <i class="glyphicon glyphicon-star text-warning"></i>
                            <i class="glyphicon glyphicon-star text-warning"></i>
                            <i class="glyphicon glyphicon-star-empty"></i>
                            <i class="glyphicon glyphicon-star-empty"></i>                    
                        </div>
                        <div class="col-md-6 text-right small">
                            1.983 Visualizações
                        </div>
                    </div>
                </div>
                <div class="panel-footer text-center">
                    <a href="" class="btn btn-primary">ABRIR EXPOSIÇÃO</a>
                </div>
            </div>
        </div>   
        
    </div>    
</section>
<section>
    <div class="row">
        <div class="col-md-12">
            <p><?php echo $this->translate("Os Grandes Artistas"); ?></p>
            <hr />
        </div>
    </div>
</section>