<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Stylish Portfolio - Start Bootstrap Theme</title>

        <!-- CSS -->
        <link href="<?php echo $this->baseUrl("views/css/bootstrap.min.css"); ?>" rel="stylesheet">        
        <link href="<?php echo $this->baseUrl("views/css/bootstrap-theme.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/style.css"); ?>" rel="stylesheet">

        <!-- Js -->
        <script src="<?php echo $this->baseUrl("views/js/jquery.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/bootstrap.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/html5shiv.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/respond.min.js"); ?>"></script>

        <?php echo $this->headScript(); ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url(array(
                            'controller' => 'index',
                            'action' => 'index'
                        ), null, true); ?>">Gallery</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url(array(
                            'controller' => 'index',
                            'action' => 'index'
                        ), null, true); ?>"><?php echo $this->translate('Sobre o Projeto') ?></a></li>
                        <li><a href="<?php echo $this->url(array(
                            'controller' => 'index',
                            'action' => 'index'
                        ), null, true); ?>"><?php echo $this->translate('Quem somos') ?></a></li>
                        <li class=""><a href="<?php echo $this->url(array(
                            'controller' => 'contato',
                            'action' => 'index'
                        ), null, true); ?>"><?php echo $this->translate('Contato') ?></a></li>
                    </ul>
                    
                    <?php //if (Zend_Auth::getInstance()->hasIdentity()) : ?>
                    <?php if (1 == 1) : ?>
                    <ul class="nav navbar-nav pull-right">
                        <li class=""><a href="<?php echo $this->url(array(
                            'controller' => 'contato',
                            'action' => 'index'
                        ), null, true); ?>"><?php echo $this->translate('Fernando Rodrigues') ?></a></li>
                    </ul>
                    <?php endif; ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->layout()->content; ?>
            <hr>
            <footer class="small">
                <div class="row">
                    <div class="col-md-6">
                        <a href="" class="">Política de Privacidade</a>                        
                        <a href="" class="">Termo de Uso</a>                        
                    </div>
                    <div class="col-md-6 text-right">
                        <?php echo $this->translate("Todos os direitos reservados"); ?>
                    </div>                    
                </div>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
